### ISSUE TITLE
Question regarding your choice for split

### ISSUE THREAD

**Issue by ashudva** [agastya1995/AV_Jobathon_Feb_2022#1]
What was the reason that you didn't choose out of fold predictions for the next stage error estimations? That could have given your regressor more data to train on.

**Comment by ashudva** [comment]
Albeit, Great Approach!
Congratulations for the Rank and maybe Job.

**Comment by agastya1995** [comment]
Thank you!

Out of fold predictions is a really good idea. Honestly, I never even considered it. At that point, I was already in the lead and running low on time, so just did the bare minimum and submitted the code.
Apart from your suggestion, I've also seen some fantastic feature engineering done in the other code files, I think implementing those will also have a massive impact on the final score.

**Comment by ashudva** [comment]
Yes, the Feature Engineering would have improved your regressor, indeed! But the crucial part was tuning the SVD parameters which I didn't and simply dropped the Idea and I can't even begin to describe how disappointed I am to see  such good scores with it.
Error estimation was a really great idea!
